services:
  pg-red:
    image: postgres:17-alpine
    command: "apk add vim && /bin/sleep 7200"
    #environment:
    #  - POSTGRES_USER=${POSTGRES_USER}
    #  - POSTGRES_PASSWORD=${POSTGRES_PW}
    #  - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    volumes:
      - "./pg-red/:/var/lib/postgresql/data"
      - "./wal-archive/:/mnt/wal-archive"
      - "./bin/:/root/bin/"
      - "./pg-red-bashrc:/root/.bashrc"
    ports:
      - "6432:5432"

  pg-green:
    image: postgres:17-alpine
    command: "apk add vim && /bin/sleep 7200"
    volumes:
      - "./pg-green/:/var/lib/postgresql/data"
      - "./wal-archive/:/mnt/wal-archive"
      - "./bin/:/root/bin/"
      - "./pg-green-bashrc:/root/.bashrc"
    ports:
      - "7432:5432"

  pg-blue:
    image: postgres:17-alpine
    command: "apk add vim && /bin/sleep 7200"
    #environment:
    #  - POSTGRES_USER=${POSTGRES_USER}
    #  - POSTGRES_PASSWORD=${POSTGRES_PW}
    #  - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    volumes:
      - "./pg-blue/:/var/lib/postgresql/data"
      - "./wal-archive/:/mnt/wal-archive"
      - "./bin/:/root/bin/"
      - "./pg-blue-bashrc:/root/.bashrc"
    ports:
      - "8432:5432"
